#spring
spring:
  devtools:
    restart:
      enabled: false
  output:
    ansi:
      enabled: never
  zipkin:
    enabled: true
    #base-url: http://10.12.21.171:2222/
  sleuth:
    sampler:
      percentage: 1
    enabled: true
  rabbitmq:
    host: 10.0.4.108
    port: 5672
    username: admin
    password: 123456
#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@10.12.21.171:1111/eureka
  instance:
    prefer-ip-address: true
    health-check-url-path: /health
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#feign
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml;application/xml;application/json
      min-request-size: 2048
    response:
      enabled: true
  httpclient:
    enable: true
#info
info:
  contact:
    email: dongmai@fangdd.com
    phone: 18616956630
management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: false
